"""
export_schema.py
-----------------
Exports the live database's actual schema (tables AND indexes) to
database/schema.sql, as a human-readable reference. This reflects
exactly what exists in the database right now — run it after any
schema change (e.g. after updating DDL in load.py or db_summary.py and
running them) to keep schema.sql in sync.

This is a documentation/reference tool, not a migration tool — it does
not modify the database, only reads its current structure and writes
it out as SQL.

Usage:
    python pipeline/export_schema.py

Input:
    database/positioning_radar.db

Output:
    database/schema.sql (overwritten)
"""

import sqlite3
from datetime import datetime
from pathlib import Path

ROOT        = Path(__file__).parent.parent
DB_PATH     = ROOT / "database" / "positioning_radar.db"
SCHEMA_PATH = ROOT / "database" / "schema.sql"


def main():
    conn = sqlite3.connect(DB_PATH)

    tables = conn.execute(
        "SELECT name, sql FROM sqlite_master "
        "WHERE type='table' AND sql IS NOT NULL "
        "AND name != 'sqlite_sequence' "
        "ORDER BY name"
    ).fetchall()
    # sqlite_sequence is SQLite's own internal bookkeeping table, auto-
    # created whenever AUTOINCREMENT is used — not part of our schema.

    # Excludes SQLite's own internal autoindexes (created implicitly for
    # PRIMARY KEY/UNIQUE constraints, not explicitly via CREATE INDEX) —
    # those have no meaningful name and aren't part of our own DDL.
    indexes = conn.execute(
        "SELECT name, sql FROM sqlite_master "
        "WHERE type='index' AND sql IS NOT NULL "
        "AND name NOT LIKE 'sqlite_autoindex%' "
        "ORDER BY name"
    ).fetchall()

    conn.close()

    with open(SCHEMA_PATH, "w", encoding="utf-8") as f:
        f.write(f"-- schema.sql\n")
        f.write(f"-- Auto-generated by pipeline/export_schema.py — do not edit by hand.\n")
        f.write(f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"-- Source: database/positioning_radar.db\n\n")

        f.write(f"-- ── Tables ───────────────────────────────────────────────────\n\n")
        for name, sql in tables:
            f.write(sql + ";\n\n")

        f.write(f"-- ── Indexes ──────────────────────────────────────────────────\n\n")
        for name, sql in indexes:
            f.write(sql + ";\n\n")

    print(f"schema.sql updated -> {len(tables)} tables, {len(indexes)} indexes")


if __name__ == "__main__":
    main()
