"""
merge_scores.py
----------------
Joins ingredient-stage composition analysis with front-of-pack vision
claim extraction to produce positioning_composition_gap.

Architecture (see docs/ADR.md ADR-010 and docs/METHODOLOGY.md):
    composition_marker_score    = Component A (0-40 pts)
                                  Source: analyze.py ingredient analysis
    pack_claims_found           = Component B input (front-of-pack claims)
                                  Source: vision_extract.py OCR + LLM
    positioning_composition_gap = Component A + B + C (0-100 pts)
                                  Computed here by merge_scores.py

Scoring:
    Component A (0-40):  Ingredient composition signal — from
                         composition_marker_score
    Component B (0-30):  Claim weight — count of front-of-pack claims,
                         weighted by claim type (see CLAIM_WEIGHTS)
    Component C (0-30):  Processing/nutrition context — additional
                         weight when claims co-occur with NOVA group 4
                         or Nutri-Score D/E reference grades

positioning_composition_gap is a composite signal, not a pure gap
metric: Component A applies regardless of whether any claim is present,
so a product with no detected pack claims can still receive a non-zero
score. Its reference band labels describe composite-signal strength,
not a claim-vs-composition comparison — see docs/METHODOLOGY.md for the
full breakdown and this known limitation.

Intersection pattern bonus:
    Each ingredient-based intersection pattern flag (computed in
    analyze.py) that co-occurs with a confirmed front-of-pack claim adds
    additional weight to Component B (capped at 30 total for Component B).

This script also writes pack-image extraction metadata
(pack_analysis_attempted, vision_model, prompt_version,
pack_analysis_timestamp, ocr_text, ocr_status, llm_status) to the
database, for every product actually submitted for extraction —
regardless of whether OCR/LLM succeeded. Result fields
(positioning_composition_gap, positioning_composition_gap_band,
pack_claims_found) are written only where LLM extraction succeeded on
this run, and are never reset to NULL by a later run that fails for the
same product — see update_db_positioning_scores().

claim_source, claim_category_1, claim_category_2,
nutrition_benchmark_flags, and claim_benchmark_intersections are NOT
written here — they are populated by tag_claims.py, which uses
pack_claims_found and pack_analysis_attempted (both written here) to do so.

powerbi_merged_<timestamp>.csv is an intermediate QA export (includes
raw v3_* extraction-schema columns for review). Final Power BI reporting
exports are generated by db_summary.py, after tag_claims.py has run.

Usage:
    python pipeline/merge_scores.py
    python pipeline/merge_scores.py --input data/reference/vision_results_20260523_210131.csv

Input:
    database/positioning_radar.db        (composition_marker_score + product data)
    data/reference/vision_results_*.csv  (archived v3 run)
    OR data/sample/vision_results_<latest>.csv  (most recent run,
    excluding vision_results_checkpoint.csv — use --input to target it
    explicitly if ever needed)

Output:
    database/positioning_radar.db  (updated with positioning_composition_gap
                                     and pack-image extraction metadata)
    data/sample/merged_results_<timestamp>.csv
    data/sample/powerbi_merged_<timestamp>.csv
"""

import argparse
import pandas as pd
import sqlite3
import os
from datetime import datetime
from pathlib import Path

ROOT       = Path(__file__).parent.parent
SAMPLE_DIR = ROOT / "data" / "sample"
REF_DIR    = ROOT / "data" / "reference"
DB_PATH    = ROOT / "database" / "positioning_radar.db"


# ── Claim weights for Component B ────────────────────────────────────────────
# Weight applied to each detected pack claim type when computing the
# claim-weight component of positioning_composition_gap. Weights are an
# analytical weighting choice reflecting how strongly each claim type
# tends to emphasize a positioning benefit — not a judgment of severity,
# wrongdoing, or legal risk. See docs/METHODOLOGY.md.
#
# Keys here mirror the locked extraction schema in vision_extract.py's
# SYSTEM_PROMPT (e.g. sustainability_halo, glp1_positioning). These are
# intermediate extraction-schema keys, not final user-facing taxonomy —
# tag_claims.py produces the neutral, public-facing claim taxonomy
# (claim_category_1, claim_category_2) from pack_claims_found.

CLAIM_WEIGHTS = {
    "protein_claim":        3,
    "no_added_sugar":       3,
    "reduced_sugar":        2,
    "fortification_claim":  2,
    "fibre_claim":          2,
    "probiotic_claim":      2,
    "natural_claim":        2,
    "vitalite_concept":     3,
    "sustainability_halo":  1,
    "reformulation_claim":  2,
    "comparative_claim":    3,
    "glp1_positioning":     3,
    "energy_claim":         1,
    "no_palm_oil":          1,
    "no_artificial":        1,
    "origin_quality_claim": 1,
    "clean_label_claim":    2,
    "artisan_claim":        1,
}

# ── Pack claim fields ─────────────────────────────────────────────────────────
# The full set of boolean claim fields produced by vision_extract.py's
# extraction schema, used to build pack_claims_found. This list
# explicitly EXCLUDES non-claim extraction metadata and non-boolean
# fields — no_claims_detected (an absence indicator, not a claim),
# ocr_quality, protein_amount_g, sugar_reduction_pct,
# comparative_reference, and the list fields fortification_nutrients /
# sustainability_certs / other_claims (handled separately, not booleans).
# These must never appear inside pack_claims_found itself.

PACK_CLAIM_FIELDS = [
    "protein_claim", "no_added_sugar", "reduced_sugar",
    "no_palm_oil", "no_artificial", "natural_claim",
    "fortification_claim", "fibre_claim", "probiotic_claim",
    "immune_claim", "energy_claim", "vitalite_concept",
    "sustainability_halo", "reformulation_claim", "comparative_claim",
    "glp1_positioning", "origin_quality_claim", "clean_label_claim",
    "minimal_ingredients_claim", "artisan_claim", "vegan_claim",
    "organic_claim", "dairy_free_claim", "plant_based_claim",
    "heritage_claim", "gluten_free_claim", "gender_targeting_claim",
]

# ── Intersection pattern bonus weights ────────────────────────────────────────
# Additional weight added to Component B when an ingredient-based
# intersection pattern flag (see analyze.py / docs/COLUMN_DESCRIPTIONS.md)
# co-occurs with a confirmed front-of-pack claim.

INTERSECTION_PATTERN_BONUS = {
    "sugar_positioning_intersection_flag":       10,
    "protein_fat_intersection_flag":             10,
    "fibre_sugar_processing_intersection_flag":  10,
    "plant_based_nutrition_intersection_flag":    8,
}


def safe_text(val):
    """
    Convert a value to a clean string for SQLite storage, or None.

    Needed because the common `str(val or "")` pattern produces the
    literal string "nan" when val is a pandas/numpy NaN float — NaN is
    truthy in Python, so `nan or ""` evaluates to nan, not "".
    """
    if pd.isna(val):
        return None
    return str(val)


def find_latest_vision_results():
    """
    Find the most recent vision results CSV across reference and sample
    folders, excluding vision_results_checkpoint.csv — an in-progress
    checkpoint file should never be auto-selected as the final result
    set, even if it happens to have the latest modification time. Use
    --input to target a checkpoint file explicitly if ever needed.
    """
    files = list(REF_DIR.glob("vision_results_*.csv")) + \
            list(SAMPLE_DIR.glob("vision_results_*.csv"))
    files = [f for f in files if "checkpoint" not in f.name]
    if not files:
        raise FileNotFoundError(
            "No vision_results_*.csv found (excluding checkpoint files). "
            "Run vision_extract.py first."
        )
    return max(files, key=lambda f: f.stat().st_mtime)


def compute_component_b(row):
    """
    Component B: claim weight (0-30 points).
    Sum of CLAIM_WEIGHTS for each front-of-pack claim detected by the
    vision pipeline, capped at 30. See docs/METHODOLOGY.md.
    """
    score = 0
    for claim, weight in CLAIM_WEIGHTS.items():
        col = f"v3_{claim}"
        if col in row.index and row[col] == True:
            score += weight
    return min(score, 30)


def compute_component_c(row):
    """
    Component C: processing/nutrition context (0-30 points).
    Adds weight when front-of-pack claims co-occur with NOVA group 4 or
    Nutri-Score D/E reference grades — only computed when Component B is
    above zero (i.e., when at least one claim is present). See
    docs/METHODOLOGY.md for the full formula and its known limitations
    as a composite rather than a pure gap metric.
    """
    score = 0
    has_any_claim = row.get("component_b", 0) > 0

    if not has_any_claim:
        return 0

    # NOVA group 4 / 3 context
    try:
        nova = float(row.get("nova_group", 0) or 0)
    except (TypeError, ValueError):
        nova = 0

    if nova == 4.0:
        score += 15
    elif nova == 3.0:
        score += 8

    # Nutri-Score D/E context
    nutriscore = str(row.get("nutriscore_grade", "") or "").upper()
    if nutriscore == "E":
        score += 10
    elif nutriscore == "D":
        score += 7

    # Comparative claim — added as context weight; the comparison
    # reference (e.g. "vs market average") is often not stated on pack.
    if row.get("v3_comparative_claim") == True:
        score += 5

    # Weight-management positioning + NOVA group 4 co-occurrence
    if row.get("v3_glp1_positioning") == True and nova == 4.0:
        score += 5

    return min(score, 30)


def compute_intersection_pattern_bonus(row):
    """
    Adds additional weight to Component B when an ingredient-based
    intersection pattern flag (computed in analyze.py) co-occurs with a
    front-of-pack claim — i.e., when the ingredient-based signal and the
    pack-image claim layer agree. See docs/METHODOLOGY.md.
    """
    bonus = 0
    for col, weight in INTERSECTION_PATTERN_BONUS.items():
        if row.get(col) == True or row.get(col) == 1:
            # Only add bonus if there's also a front-of-pack claim
            if row.get("component_b", 0) > 0:
                bonus += weight
    return bonus


def classify_positioning_composition_gap_band(score):
    """
    Map positioning_composition_gap to a neutral reference band.
    Labels describe composite-signal strength, not a claim-vs-
    composition comparison — see module docstring and docs/METHODOLOGY.md.
    """
    if score >= 70:
        return "High positioning-composition signal"
    elif score >= 45:
        return "Moderate positioning-composition signal"
    elif score >= 20:
        return "Low positioning-composition signal"
    else:
        return "Minimal positioning-composition signal"


def get_pack_claims_found(row):
    """
    Build the pipe-separated pack_claims_found string from PACK_CLAIM_FIELDS
    only — never from the full set of v3_ columns, which also includes
    non-claim extraction metadata (no_claims_detected, ocr_quality, etc.)
    that must not be treated as a claim.
    """
    claims = []
    for key in PACK_CLAIM_FIELDS:
        col = f"v3_{key}"
        if col in row.index and row[col] == True:
            claims.append(key)
    return "|".join(claims) if claims else ""


def load_db_data(conn):
    """Load products + ingredient-stage analysis from SQLite."""
    df = pd.read_sql("""
        SELECT
            p.barcode, p.product_name, p.brands, p.primary_brand,
            p.query_category, p.primary_country,
            p.nova_group, p.nutriscore_grade,
            p.energy_kcal, p.sugars_100g, p.protein_100g,
            p.saturated_fat_100g, p.image_url,
            a.composition_marker_score,
            a.processing_markers_found,
            a.ingredient_based_claim_signals_found,
            a.absence_reduction_claims_found,
            a.sugar_positioning_intersection_flag,
            a.protein_fat_intersection_flag,
            a.fibre_sugar_processing_intersection_flag,
            a.plant_based_nutrition_intersection_flag
        FROM products p
        LEFT JOIN product_analysis a ON p.barcode = a.barcode
    """, conn, dtype={"barcode": str})
    return df


def update_db_positioning_scores(conn, merged_df, timestamp):
    """
    Write pack-image extraction results back to the product_analysis
    table, via two separate update paths so a failed rerun can never
    erase a previously successful result.

    Path 1 — attempt metadata: written for every row attempted this run
    (present in the vision_results CSV), regardless of OCR/LLM outcome.
    pack_analysis_attempted, vision_model, prompt_version,
    pack_analysis_timestamp, ocr_text, ocr_status, llm_status, analyzed_at.

    Path 2 — result fields: written ONLY for rows where LLM extraction
    succeeded on this run. Rows that were attempted but failed this run
    are simply not touched by this path, so any result from an earlier
    successful run is preserved rather than overwritten with NULL.
    positioning_composition_gap, positioning_composition_gap_band,
    pack_claims_found.

    claim_source, claim_category_1, claim_category_2,
    nutrition_benchmark_flags, and claim_benchmark_intersections are NOT
    written here — see module docstring.
    """
    cursor = conn.cursor()
    updated = 0

    attempted = merged_df[merged_df["llm_status"].notna()]

    for _, row in attempted.iterrows():
        # Path 1: attempt metadata, always written for attempted rows.
        cursor.execute("""
            UPDATE product_analysis
            SET pack_analysis_attempted = 1,
                vision_model = ?,
                prompt_version = ?,
                pack_analysis_timestamp = ?,
                ocr_text = ?,
                ocr_status = ?,
                llm_status = ?,
                analyzed_at = ?
            WHERE barcode = ?
        """, (
            safe_text(row.get("vision_model")),
            safe_text(row.get("prompt_version")),
            safe_text(row.get("pack_analysis_timestamp")),
            safe_text(row.get("ocr_text")),
            safe_text(row.get("ocr_status")),
            safe_text(row.get("llm_status")),
            timestamp,
            str(row["barcode"])
        ))

        # Path 2: result fields, only written on success this run —
        # never overwrites a prior successful result with NULL.
        has_result = pd.notna(row.get("positioning_composition_gap"))
        if has_result:
            cursor.execute("""
                UPDATE product_analysis
                SET positioning_composition_gap = ?,
                    positioning_composition_gap_band = ?,
                    pack_claims_found = ?
                WHERE barcode = ?
            """, (
                float(row["positioning_composition_gap"]),
                str(row["positioning_composition_gap_band"]),
                safe_text(row.get("pack_claims_found")) or "",
                str(row["barcode"])
            ))

        updated += 1

    conn.commit()
    return updated


def main():
    parser = argparse.ArgumentParser(
        description="Merge ingredient-stage analysis with vision results"
    )
    parser.add_argument(
        "--input", type=str, default=None,
        help="Path to a specific vision_results CSV (default: auto-detect "
             "latest, excluding checkpoint files)"
    )
    args = parser.parse_args()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    print(f"\nFood & Beverage Positioning Radar - merge_scores.py")
    print(f"Run timestamp: {timestamp}")
    print(f"Computing positioning_composition_gap from composition_marker_score + vision results\n")

    # ── Load vision results ───────────────────────────────────────────────────
    vision_path = Path(args.input) if args.input else find_latest_vision_results()
    print(f"  Vision results: {vision_path.name}")
    vision = pd.read_csv(vision_path, dtype={"barcode": str}, low_memory=False)
    print(f"  Vision rows: {len(vision):,}")

    ocr_ok  = (vision["ocr_status"] == "success").sum()
    llm_ok  = (vision["llm_status"] == "success").sum()
    print(f"  OCR success: {ocr_ok:,} | LLM success: {llm_ok:,}")

    # ── Load DB data ──────────────────────────────────────────────────────────
    print(f"\n  Loading product + ingredient-stage analysis from DB...")
    conn = sqlite3.connect(DB_PATH)
    db_df = load_db_data(conn)
    print(f"  DB rows: {len(db_df):,}")

    # ── Merge on barcode ──────────────────────────────────────────────────────
    print(f"\n  Merging on barcode...")

    # Keep v3_ raw claim columns plus any available extraction metadata.
    # Metadata columns (vision_model, prompt_version,
    # pack_analysis_timestamp) are present for any run using the current
    # vision_extract.py; may be absent if reusing an older archived
    # vision_results CSV — handled gracefully via row.get()/safe_text().
    v3_cols = [c for c in vision.columns if c.startswith("v3_")]
    metadata_cols = [c for c in [
        "vision_model", "prompt_version", "pack_analysis_timestamp",
    ] if c in vision.columns]

    vision_slim = vision[
        ["barcode", "ocr_text", "ocr_status", "llm_status"] +
        metadata_cols + v3_cols
    ].copy()

    merged = db_df.merge(vision_slim, on="barcode", how="left")
    vision_matched = merged["llm_status"].notna().sum()
    print(f"  Products with vision data: {vision_matched:,}")
    print(f"  Products without vision data: {(merged['llm_status'].isna()).sum():,}")

    # ── Compute positioning_composition_gap ───────────────────────────────────
    print(f"\n  Computing positioning_composition_gap...")

    # has_vision: LLM extraction succeeded for this row.
    # Rows not in has_vision but present in the merge (attempted, OCR or
    # LLM failed) still get attempt metadata written — see
    # update_db_positioning_scores().
    has_vision = merged["llm_status"] == "success"

    merged["pack_claims_found"] = merged.apply(
        lambda row: get_pack_claims_found(row) if has_vision[row.name] else None,
        axis=1
    )

    # Component B
    merged["component_b"] = merged.apply(
        lambda row: compute_component_b(row) if has_vision[row.name] else 0,
        axis=1
    )

    # Intersection pattern bonus
    merged["pattern_bonus"] = merged.apply(compute_intersection_pattern_bonus, axis=1)

    # Adjusted Component B
    merged["component_b_adj"] = (merged["component_b"] +
                                  merged["pattern_bonus"]).clip(upper=30)

    # Component C
    merged["component_c"] = merged.apply(
        lambda row: compute_component_c(row) if has_vision[row.name] else 0,
        axis=1
    )

    # Final positioning_composition_gap
    merged["composition_marker_score"] = pd.to_numeric(
        merged["composition_marker_score"], errors="coerce"
    ).fillna(0)

    merged["positioning_composition_gap"] = merged.apply(
        lambda row: (
            row["composition_marker_score"] +
            row["component_b_adj"] +
            row["component_c"]
        ) if has_vision[row.name] else None,
        axis=1
    )

    merged["positioning_composition_gap_band"] = merged["positioning_composition_gap"].apply(
        lambda s: classify_positioning_composition_gap_band(s) if pd.notna(s) else None
    )

    # ── Summary statistics ────────────────────────────────────────────────────
    scored = merged[merged["positioning_composition_gap"].notna()].copy()
    scored["positioning_composition_gap"] = pd.to_numeric(
        scored["positioning_composition_gap"], errors="coerce"
    )

    print(f"\n  -- Positioning-composition gap summary ------------------------")
    print(f"  Products with a gap score: {len(scored):,}")

    dist = scored["positioning_composition_gap_band"].value_counts()
    print(f"\n  Band distribution:")
    for band, n in dist.items():
        print(f"    {band:<40} {n:,}")

    print(f"\n  Component B+C contribution (gap minus composition_marker_score):")
    contribution = scored["positioning_composition_gap"] - scored["composition_marker_score"]
    print(f"    Mean contribution:   {contribution.mean():.1f} points")
    print(f"    Max contribution:    {contribution.max():.1f} points")
    print(f"    Products with contribution > 20:  {(contribution > 20).sum():,}")

    print(f"\n  Products with high positioning-composition composite signal "
          f"(sample for review):")
    top = scored.nlargest(15, "positioning_composition_gap")[
        ["product_name", "brands", "composition_marker_score",
         "positioning_composition_gap", "pack_claims_found"]
    ]
    pd.set_option("display.max_colwidth", 35)
    print("  " + top.to_string().replace("\n", "\n  "))

    print(f"\n  Brand-level positioning-composition summary "
          f"(highest averages shown for QA, min 5 products with vision):")
    brand_stats = scored.groupby("primary_brand").agg(
        avg_gap=("positioning_composition_gap", "mean"),
        avg_composition=("composition_marker_score", "mean"),
        n=("barcode", "count")
    ).reset_index()
    brand_stats = brand_stats[brand_stats["n"] >= 5].sort_values(
        "avg_gap", ascending=False
    ).head(10)
    for _, row in brand_stats.iterrows():
        contribution_brand = row["avg_gap"] - row["avg_composition"]
        print(f"    {str(row['primary_brand']):<25} "
              f"composition={row['avg_composition']:.1f} → gap={row['avg_gap']:.1f} "
              f"(+{contribution_brand:.1f})  n={int(row['n'])}")

    # ── Intersection pattern summary ──────────────────────────────────────────
    print(f"\n  Intersection patterns confirmed by vision (ingredient-based flag")
    print(f"  co-occurring with at least one front-of-pack claim):")
    for col, label in [
        ("sugar_positioning_intersection_flag",          "Sugar positioning intersection"),
        ("protein_fat_intersection_flag",                "Protein/fat intersection"),
        ("fibre_sugar_processing_intersection_flag",     "Fibre/processing intersection"),
        ("plant_based_nutrition_intersection_flag",      "Plant-based/nutrition intersection"),
    ]:
        pattern_with_claims = scored[
            (scored[col].isin([True, 1])) &
            (scored["component_b"] > 0)
        ]
        print(f"    {label}: {len(pattern_with_claims):,}")

    # ── Write results to DB ───────────────────────────────────────────────────
    print(f"\n  Writing pack-image results to database...")
    updated = update_db_positioning_scores(conn, merged, timestamp)
    print(f"  Updated {updated:,} rows in product_analysis")
    conn.close()

    # ── Save merged CSV ───────────────────────────────────────────────────────
    output_path = SAMPLE_DIR / f"merged_results_{timestamp}.csv"
    merged.to_csv(output_path, index=False, encoding="utf-8-sig")
    print(f"\n  Saved -> merged_results_{timestamp}.csv")
    print(f"  ({len(merged):,} rows)")

    # Power BI friendly export — scored products only. This is an
    # intermediate QA export (includes raw v3_* extraction-schema
    # columns); final reporting exports come from db_summary.py after
    # tag_claims.py has run — see module docstring.
    pbi_cols = [
        "barcode", "product_name", "brands", "primary_brand",
        "query_category", "primary_country", "nova_group", "nutriscore_grade",
        "energy_kcal", "sugars_100g", "protein_100g", "saturated_fat_100g",
        "image_url", "composition_marker_score", "positioning_composition_gap",
        "positioning_composition_gap_band", "component_b_adj", "component_c",
        "pack_claims_found", "processing_markers_found",
        "sugar_positioning_intersection_flag", "protein_fat_intersection_flag",
        "fibre_sugar_processing_intersection_flag",
        "plant_based_nutrition_intersection_flag",
    ] + [c for c in v3_cols if c in merged.columns]

    pbi_cols = [c for c in pbi_cols if c in merged.columns]
    pbi_df = scored[pbi_cols].copy()
    pbi_path = SAMPLE_DIR / f"powerbi_merged_{timestamp}.csv"
    pbi_df.to_csv(pbi_path, index=False, encoding="utf-8-sig")
    print(f"  Power BI export (intermediate QA) -> powerbi_merged_{timestamp}.csv")
    print(f"  ({len(pbi_df):,} rows)\n")
    print(f"  Done. positioning_composition_gap is now in the database.\n")


if __name__ == "__main__":
    main()
