"""
vision_extract.py
------------------
Two-stage front-of-pack claim and positioning-signal extraction pipeline.

Stage 1: Azure AI Vision Read API (OCR)
    Extracts raw text from product front-of-pack images.
    Cost: ~1.50 CHF / 1,000 images (historical estimate, see below).

Stage 2: Azure OpenAI (gpt-4.1-nano) on extracted text
    Parses OCR text into structured claim JSON.
    Much cheaper than sending images directly to a vision-capable model.

Cost figures throughout this file are historical project estimates from
the v3 run, not a pricing guarantee — confirm current pricing before any
larger rerun.

Input:
    data/sample/smart_sample_<timestamp>.csv
    (generated by smart_sample.py)

Output:
    data/sample/vision_results_<timestamp>.csv
    - barcode, product_name, brands, tier (sampling tier from smart_sample.py)
    - pack_analysis_attempted, vision_model, prompt_version,
      pack_analysis_timestamp
    - ocr_text: raw text from Azure Vision
    - claims_json: structured claims from the LLM extraction step
    - claims flattened into individual v3_* columns (intermediate/debug
      fields — see note above the flattening block below)
    - ocr_status, llm_status

Usage:
    # Test on a stratified 100-product sample first (50 per region)
    python pipeline/vision_extract.py --test

    # Full run
    python pipeline/vision_extract.py

    # Resume interrupted run from a checkpoint
    python pipeline/vision_extract.py --resume

Environment variables required:
    AZURE_VISION_ENDPOINT    e.g. https://your-resource.cognitiveservices.azure.com/
    AZURE_VISION_KEY         32-character key from Azure portal
    AZURE_OPENAI_ENDPOINT    e.g. https://your-resource.openai.azure.com/
    AZURE_OPENAI_KEY         key from Azure OpenAI portal
    AZURE_OPENAI_DEPLOYMENT  e.g. gpt-4.1-nano

    OR set them in a .env file in the project root.

Cost controls:
    Set AZURE_COST_ALERT_CHF to stop processing when estimated cost
    exceeds that value. Default is set below the v3.5 model-benchmark
    budget (see docs/ADR.md) to leave a buffer. Hard stop before
    credits run out.

    Cost-per-1000 figures below are historical estimates from the v3
    run, not a pricing guarantee — LLM pricing changes over time and
    should be reconfirmed before any larger rerun. See also
    smart_sample.py, which uses the same historical baseline.

See docs/ADR.md ADR-006 and ADR-010 for architecture rationale.
"""

import os
import sys
import json
import time
import argparse
import requests
import pandas as pd
from datetime import datetime
from pathlib import Path

# ── Load .env if present ──────────────────────────────────────────────────────
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # dotenv optional — can set env vars directly

ROOT       = Path(__file__).parent.parent
SAMPLE_DIR = ROOT / "data" / "sample"

# ── Azure configuration ───────────────────────────────────────────────────────

VISION_ENDPOINT   = os.getenv("AZURE_VISION_ENDPOINT", "").rstrip("/")
VISION_KEY        = os.getenv("AZURE_VISION_KEY", "")
OPENAI_ENDPOINT   = os.getenv("AZURE_OPENAI_ENDPOINT", "").rstrip("/")
OPENAI_KEY        = os.getenv("AZURE_OPENAI_KEY", "")
OPENAI_DEPLOYMENT = os.getenv("AZURE_OPENAI_DEPLOYMENT", "gpt-4.1-nano")
COST_ALERT_CHF    = float(os.getenv("AZURE_COST_ALERT_CHF", "45"))

# Increment when SYSTEM_PROMPT changes. This is the original, locked
# extraction prompt used for the v3 run (see docs/ADR.md ADR-006) —
# do not change the prompt text itself without also bumping this.
PROMPT_VERSION = "v4"

# Cost per 1000 operations (CHF estimates).
# OCR_COST_PER_1K is Azure AI Vision Read API's published per-image rate.
# LLM_COST_PER_1K is derived from the actual v3 run total (~8 CHF for
# ~4,700 products with gpt-4.1-nano, combined OCR+LLM ≈ 1.70 CHF/1,000 —
# see smart_sample.py ACTUAL_COST_PER_1000_CHF) minus the OCR component.
# Historical estimate, not a pricing guarantee — confirm current Azure
# OpenAI pricing before any larger rerun.
OCR_COST_PER_1K   = 1.50
LLM_COST_PER_1K   = 0.20

# ── System prompt for LLM claim extraction ────────────────────────────────────
# This prompt is locked — it is known to perform well and should not be
# edited casually. Its raw JSON field names (e.g. sustainability_halo,
# glp1_positioning, vitalite_concept) are extraction-schema keys, not
# final product language; see the note above the flattening block below.

SYSTEM_PROMPT = """You are a food labelling analyst. You receive OCR text extracted
from a packaged food product. Extract health and marketing claims.

Return ONLY valid JSON with this exact structure:
{
  "image_context": "front_of_pack | mixed_pack_text | ingredient_or_legal_panel | nutrition_label | price_sticker | uncertain",
  "claim_extraction_status": "completed | not_applicable_non_front | unreadable",
  "protein_claim": true/false,
  "protein_amount_g": null or number (grams per 100g or per serving if stated),
  "sugar_free_claim": true/false,
  "reduced_sugar": true/false,
  "sugar_reduction_pct": null or number (e.g. 32 for "-32%"),
  "no_palm_oil": true/false,
  "no_artificial": true/false,
  "natural_claim": true/false,
  "fortification_claim": true/false,
  "fortification_nutrients": [] or list of nutrient names,
  "fibre_claim": true/false,
  "gut_health_claim": true/false,
  "probiotic_claim": true/false,
  "prebiotic_claim": true/false,
  "immune_claim": true/false,
  "energy_claim": true/false,
  "sleep_claim": true/false,
  "brain_health_claim": true/false,
  "vitalite_concept": true/false,
  "sustainability_halo": true/false,
  "sustainability_certs": [] or list,
  "reformulation_claim": true/false,
  "comparative_claim": true/false,
  "comparative_reference": null or string,
  "glp1_positioning": true/false,
  "vegan_claim": true/false,
  "organic_claim": true/false,
  "dairy_free_claim": true/false,
  "lactose_free_claim": true/false,
  "plant_based_claim": true/false,
  "heritage_claim": true/false,
  "gluten_free_claim": true/false,
  "gender_targeting_claim": true/false,
  "minimal_ingredients_claim": true/false,
  "origin_quality_claim": true/false,
  "clean_label_claim": true/false,
  "artisan_claim": true/false,
  "detected_claim_phrases": [],
  "reduced_fat_claim": true/false,
  "fat_reduction_pct": null or number (e.g. 30 for "-30% fat vs reference"),
  "whole_grain_claim": true/false,
  "other_claims": [] or list of short strings for claims that do not fit any field above,
  "no_claims_detected": true/false/null,
  "ocr_quality": "good"/"partial"/"poor"
}

IMAGE TEXT CONTEXT — CLASSIFY THIS FIRST

Determine what kind of pack text the OCR represents before extracting claims.

Allowed image_context values:

- front_of_pack:
  Primarily short product-name, benefit, claim, certification or marketing
  phrases that could reasonably appear on the consumer-facing front panel.

- mixed_pack_text:
  Contains both genuine marketing claims and substantial legal information.
  Extract only clearly separated marketing claims. Ignore nutrient names and
  ingredients appearing only inside legal text or tables.

- ingredient_or_legal_panel:
  Primarily an ingredient list, allergen declaration, storage instructions,
  manufacturer/importer details or another legal information label.

- nutrition_label:
  Primarily nutrition-table rows containing energy/kJ/kcal, fat, saturated fat,
  carbohydrate, sugars, protein, salt and repeated numeric values.

- price_sticker:
  Primarily retailer, price, weight, unit-price, date, barcode or shelf-label
  information.

- uncertain:
  The OCR does not provide enough evidence to classify the panel reliably.

Ingredient/legal-panel clues include:
- starts with INGREDIENTS / INGRÉDIENTS / ZUTATEN / INGREDIENTI or equivalent;
- long comma- or semicolon-separated text;
- many percentages, parentheses, additives, allergens or "may contain" phrases;
- storage, address, importer or manufacturer details.

A text length above 25 words is supporting evidence only. Do NOT classify a
text as a legal panel solely because it is long.

FRONT-OF-PACK NUTRITION INFORMATION
A small front-of-pack nutrition box, traffic-light panel, nutrient summary,
or row of nutrient values does not make the image a nutrition_label.
If the product branding and consumer-facing front panel are clearly visible,
classify the image as front_of_pack and ignore the nutrient values when
extracting claims.

SMALL LEGAL TEXT ON AN OTHERWISE VALID FRONT PACK
A small ingredients, nutrition, legal, recycling, or manufacturer-information
block at the bottom or side of an otherwise clear front pack does not make the
whole image ingredient_or_legal_panel.
If prominent consumer-facing marketing text is present, classify the image as
mixed_pack_text and extract only the clearly marketing-oriented statements.
Classify according to the dominant purpose of the photographed panel, not
merely because some small legal text was successfully read by OCR.

If image_context is ingredient_or_legal_panel, nutrition_label or price_sticker:
- set claim_extraction_status="not_applicable_non_front";
- set every claim field to false;
- return empty lists and null numeric values;
- set no_claims_detected=null;
- do not treat nutrient or ingredient names as claims.

If image_context is uncertain or the OCR is unreadable (mostly garbled characters):
- set claim_extraction_status="unreadable";
- set every claim field to false;
- set no_claims_detected=null;
- set ocr_quality="poor".

Only set claim_extraction_status="completed" when front-of-pack marketing
content can be assessed.

IMPORTANT: Do not set a claim based solely on the reference product name. A
claim must also be present in the OCR text being analysed.

General extraction rules:
- Do NOT infer claims — only extract what is explicitly stated in the OCR text
- Set no_claims_detected=true if you find NO health/wellness claims at all on a
  valid front-of-pack image (claim_extraction_status="completed")
- CRITICAL: if ANY specific claim field is set to true, no_claims_detected MUST
  be false. no_claims_detected=true ONLY when every other claim field is false.
- no_claims_detected=null when claim_extraction_status is not "completed"
- Set ocr_quality=poor if the text is mostly garbled or unreadable
- detected_claim_phrases: list up to 5 short phrases copied from the OCR that
  triggered claim fields. Keep each under 10 words. Do not explain reasoning.
- Return ONLY the JSON object, no explanation, no markdown fences

FUNCTIONAL BENEFIT CLAIMS:

Protein:
- "HIGH PROTEIN", "RICH IN PROTEIN", "SOURCE OF PROTEIN", "HIGH IN PROTEIN",
  "RICHE EN PROTÉINES", "SOURCE DE PROTÉINES", "+PROTEIN" = protein_claim

Fibre:
- "HIGH FIBRE", "HIGH FIBER", "SOURCE OF FIBRE", "RICHE EN FIBRES",
  "HIGH IN FIBRE", "ADDED FIBRE" = fibre_claim

Gut health (three distinct raw fields, all roll up to gut_health):
- gut_health_claim: "GUT HEALTH", "DIGESTIVE HEALTH", "SUPPORTS DIGESTION",
  "DIGESTIVE COMFORT", "HEALTHY DIGESTION", "MICROBIOME SUPPORT",
  "INTESTINAL FLORA", "REGULARITY", "TRANSIT SUPPORT", "INTESTINAL FUNCTION"
  when expressed as a BENEFIT. NOTE: "digestive biscuits" or "digestive" used
  only as a product type is NOT a gut_health_claim.
- probiotic_claim: "PROBIOTIC", "LIVE CULTURES", "ACTIVE CULTURES", prominently
  highlighted L. CASEI, BIFIDUS or named probiotic cultures as a feature.
  "PROBIOTIQUE", "PROBIOTISCH" = probiotic_claim.
  Do not infer probiotic positioning merely from ingredient list entries.
- prebiotic_claim: "PREBIOTIC", "PREBIOTIC FIBRE", "FEEDS BENEFICIAL BACTERIA",
  "SUPPORTS BENEFICIAL GUT BACTERIA" = prebiotic_claim.
  Do not infer prebiotic positioning merely because inulin or chicory root
  appears in the ingredient list.

Immunity — keep separate from fortification:
- immune_claim ONLY when wording is: "IMMUNE SUPPORT", "SUPPORTS THE IMMUNE
  SYSTEM", "IMMUNITY", "NATURAL DEFENCES", "HELPS PROTECT", "IMMUNE DEFENCE",
  "SYSTÈME IMMUNITAIRE", "DEFENSAS", "DIFESE"
- Highlighted vitamins C/D, zinc or selenium WITHOUT explicit immunity wording
  are fortification_claim ONLY, not immune_claim.

Energy:
- "SLOW RELEASE", "4 HOURS OF STEADY ENERGY", "TOUTE LA MATINÉE",
  "STEADY ENERGY", "ACTIVGO", "MORE POWER" = energy_claim

Reduced fat:
- reduced_fat_claim: "REDUCED FAT", "LOWER FAT", "LESS FAT", "LOW FAT",
  "LIGHT", "LITE", "FAT FREE", "ALLÉGÉ EN MATIÈRES GRASSES",
  "RÉDUIT EN MATIÈRES GRASSES", "MOINS DE GRAISSES", "X% LESS FAT" = reduced_fat_claim.
  Set fat_reduction_pct to the number if stated (e.g. 30 for "-30%").
  Do not use "light" as a reduced-fat signal for coffee, beer, or any product
  where "light" describes a flavour, roast level or alcohol content.

Whole grain:
- whole_grain_claim: "WHOLE GRAIN", "WHOLEGRAIN", "WHOLE WHEAT", "WHOLEWHEAT",
  "100% WHOLE GRAIN", "MADE WITH WHOLE GRAINS", "GRAINS ENTIERS",
  "CÉRÉALES COMPLÈTES", "BLÉ COMPLET" = whole_grain_claim.
  Do not classify "ANCIENT GRAINS", "MULTIGRAIN" or "MULTI-GRAIN" as
  whole_grain_claim unless the text explicitly says "whole grain."

Sleep (new field):
- sleep_claim: "SLEEP SUPPORT", "RESTFUL SLEEP", "SUPPORTS SLEEP QUALITY",
  "HELPS YOU SLEEP", "BEDTIME SUPPORT", "NIGHT-TIME RELAXATION",
  "SLEEP QUALITY" = sleep_claim.
  Do not infer a sleep claim solely from melatonin, magnesium, L-theanine,
  chamomile or the word "night" used as a flavour or product name.

Brain/cognitive health (new field):
- brain_health_claim: "BRAIN HEALTH", "COGNITIVE HEALTH", "SUPPORTS MEMORY",
  "FOCUS", "CONCENTRATION", "MENTAL PERFORMANCE", "COGNITIVE FUNCTION" when
  expressed as a BENEFIT = brain_health_claim.
  Highlighted OMEGA-3 without an explicit brain/cognitive statement is a
  fortification_claim only. Do not infer brain_health_claim from omega-3 alone.
  Do not classify vague words such as "smart", "clever" or "power" as a
  brain-health claim unless the cognitive benefit is explicit.

FORTIFICATION CLAIMS — explicit nutrient highlights (not nutrition-table values):
- "CALCIUM", "+CALCIUM", "RICHE EN CALCIUM", "HIGH IN CALCIUM" = fortification_claim,
  add "Calcium" to fortification_nutrients
- Any highlighted vitamin letter or group = fortification_claim
- "MAGNÉSIUM", "FER", "ZINC", "SÉLÉNIUM", "OMÉGA-3", "OMEGA-3" when highlighted
  as a benefit = fortification_claim
- "OPTI-START", "OPTI-GROW", "OPTI-DÉJ" (Nestlé proprietary concepts) = fortification_claim
- Rule: if a nutrient name appears prominently OUTSIDE a nutrition facts table,
  it is a fortification claim. Nutrient names appearing ONLY inside a nutrition
  table are not claims.

FREE-FROM / CLEAN LABEL:
- "SANS CONSERVATEURS", "NO PRESERVATIVES", "SENZA CONSERVANTI" = no_artificial=true
- "SANS COLORANTS", "NO ARTIFICIAL COLOURS" = no_artificial=true
- "SANS ARÔMES ARTIFICIELS", "NO ARTIFICIAL FLAVOURS" = no_artificial=true
- "SANS ADDITIFS", "NO ADDITIVES" = no_artificial=true AND clean_label_claim=true
- "ZERO SWEETENERS" alone does NOT mean sugar_free_claim — add "zero_sweeteners" to other_claims
- "DOUBLE ZERO" = only set sugar_free_claim=true AND no_artificial=true when the OCR
  also states what the two zeros refer to (e.g. "0% sugar, 0% fat"). Otherwise
  add "double_zero" to other_claims without setting specific claim fields.
- "SANS HUILE DE PALME", "NO PALM OIL" = no_palm_oil

FRENCH & EUROPEAN ORIGIN CLAIMS:
- "100% FRANÇAIS", "PRODUIT EN FRANCE", "FABRIQUÉ EN FRANCE" = origin_quality_claim
- "LAIT FRANÇAIS", "LAIT DE VACHE FRANÇAISE", "VACHES FRANÇAISES" = origin_quality_claim
- "LAIT FRAIS", "LAIT FRAIS & CRÈME" = origin_quality_claim (fresh milk claim)
- "ORIGINE FRANCE", "FILIÈRE FRANÇAISE", "AGRICULTEURS FRANÇAIS" = origin_quality_claim
- "SCHWEIZER MILCH", "LAIT SUISSE" = origin_quality_claim

REFORMULATION / NEW RECIPE:
- "NOUVELLE RECETTE", "NEW RECIPE", "NEUE REZEPTUR" = reformulation_claim
- "NOUVEAU", "NOUVEAUTÉ", "NEW", "NEU" on a product = reformulation_claim
- "ENCORE MEILLEUR", "EVEN BETTER", "IMPROVED RECIPE" = reformulation_claim AND comparative_claim

SUGAR / COMPARATIVE:
- "NO ADDED SUGAR", "WITHOUT ADDED SUGAR", "SANS SUCRES AJOUTÉS",
  "OHNE ZUCKERZUSATZ", "SENZA ZUCCHERI AGGIUNTI", "NO ADDED SUGARS",
  "SUGAR FREE", "SUGAR-FREE", "ZÉRO SUCRE", "SANS SUCRE", "ZUCKERFREI" = sugar_free_claim
- "MOINS DE SUCRES", "ALLÉGÉ EN SUCRES", "-X% SUCRES", "REDUCED SUGAR",
  "LESS SUGAR" = reduced_sugar; also set comparative_claim=true and
  sugar_reduction_pct to the number if stated
- "#1", "N°1", "NO. 1", "NUMÉRO 1" = comparative_claim

FREE-FROM / IDENTITY:
- "VEGAN", "100% VEGAN", "VÉGAN", "VEGANO" = vegan_claim
- "PLANT-BASED", "PLANT BASED", "À BASE DE PLANTES", "PFLANZENBASIERT",
  "BASE VÉGÉTALE" = plant_based_claim
- "DAIRY-FREE", "DAIRY FREE", "NON-DAIRY", "SANS PRODUITS LAITIERS" = dairy_free_claim
- "LACTOSE FREE", "LACTOSE-FREE", "SANS LACTOSE", "LAKTOSEFREI",
  "LACTOSEVRIJ" = lactose_free_claim
- "GLUTEN-FREE", "GLUTEN FREE", "SANS GLUTEN", "GLUTENFREI", "SENZA GLUTINE" = gluten_free_claim

NATURAL / CLEAN LABEL:
- "100% NATURAL", "ALL NATURAL", "NATURAL INGREDIENTS", "INGRÉDIENTS NATURELS",
  "NATÜRLICHE ZUTATEN", "INGREDIENTI NATURALI" = natural_claim
- "100% NATURAL" alone on a US/UK product IS a natural_claim (unlike French "nature")
- "NATURE" alone on French/Belgian/Swiss packaging means "plain/unflavored" — NOT natural_claim
- "CLEAN LABEL", "SIMPLE INGREDIENTS", "NOTHING ARTIFICIAL",
  "INGREDIENTS YOU CAN SEE" = clean_label_claim
- "3 INGRÉDIENTS", "3 INGREDIENTS", "NUR 3 ZUTATEN", "ONLY X INGREDIENTS" = minimal_ingredients_claim

OTHER:
- "VITALITÉ", "VITALITE" = vitalite_concept
- "ENGAGÉ CACAO DURABLE", "FILIÈRE DURABLE" = sustainability_halo
- "CREATED FOR WOMEN", "POUR LES FEMMES" = gender_targeting_claim
- "POUR LE GOÛTER", "KIDS", "POUR LES ENFANTS", "CROISSANCE" = add to other_claims
- "+X% free", "+X% gratuit", "BONUS PACK" = add to other_claims only, NOT comparative_claim
- Capture organic/bio: "bio", "organic", "biologique", "biologisch" = organic_claim
- Capture heritage: "the original", "since 19xx", "established" = heritage_claim"""


# ── Azure Vision OCR ──────────────────────────────────────────────────────────

def ocr_image(image_url: str, max_retries: int = 3) -> tuple[str, str]:
    """
    Call Azure AI Vision Read API to extract text from image URL.
    Returns (ocr_text, status) where status is 'success'/'failed'/'invalid_url'.
    """
    if not VISION_ENDPOINT or not VISION_KEY:
        return "", "no_credentials"

    if not image_url or "/invalid/" in image_url:
        return "", "invalid_url"

    url = f"{VISION_ENDPOINT}/vision/v3.2/read/analyze"
    headers = {
        "Ocp-Apim-Subscription-Key": VISION_KEY,
        "Content-Type": "application/json",
    }
    body = {"url": image_url}

    for attempt in range(max_retries):
        try:
            # Submit job
            resp = requests.post(url, headers=headers, json=body, timeout=30)

            if resp.status_code == 202:
                # Poll for result
                result_url = resp.headers.get("Operation-Location")
                if not result_url:
                    return "", "no_operation_url"

                for _ in range(10):
                    time.sleep(2)
                    result = requests.get(
                        result_url,
                        headers={"Ocp-Apim-Subscription-Key": VISION_KEY},
                        timeout=30
                    )
                    result_data = result.json()
                    status = result_data.get("status", "")
                    if status == "succeeded":
                        lines = []
                        for page in result_data.get("analyzeResult", {}).get("readResults", []):
                            for line in page.get("lines", []):
                                lines.append(line.get("text", ""))
                        return "\n".join(lines), "success"
                    elif status == "failed":
                        return "", "ocr_failed"
                return "", "ocr_timeout"

            elif resp.status_code == 429:
                wait = int(resp.headers.get("Retry-After", 60))
                print(f"      Rate limited — waiting {wait}s...")
                time.sleep(wait)
                continue

            elif resp.status_code in (400, 415):
                return "", "invalid_image"

            else:
                return "", f"http_{resp.status_code}"

        except requests.exceptions.Timeout:
            if attempt < max_retries - 1:
                time.sleep(5)
                continue
            return "", "timeout"
        except Exception as e:
            return "", f"error_{str(e)[:30]}"

    return "", "max_retries"


# ── LLM claim extraction ───────────────────────────────────────────────────────


BOOL_CLAIM_FIELDS = [
    "protein_claim", "sugar_free_claim", "reduced_sugar", "no_palm_oil",
    "no_artificial", "natural_claim", "fortification_claim", "fibre_claim",
    "gut_health_claim", "probiotic_claim", "prebiotic_claim",
    "immune_claim", "energy_claim", "sleep_claim", "brain_health_claim",
    "vitalite_concept", "sustainability_halo", "reformulation_claim",
    "comparative_claim", "glp1_positioning", "origin_quality_claim",
    "clean_label_claim", "minimal_ingredients_claim", "artisan_claim",
    "vegan_claim", "organic_claim", "dairy_free_claim", "lactose_free_claim",
    "plant_based_claim", "heritage_claim", "gluten_free_claim",
    "gender_targeting_claim", "reduced_fat_claim", "whole_grain_claim",
    "no_claims_detected",
]

VALID_IMAGE_CONTEXTS = {
    "front_of_pack", "mixed_pack_text", "ingredient_or_legal_panel",
    "nutrition_label", "price_sticker", "uncertain",
}
VALID_CLAIM_STATUSES = {"completed", "not_applicable_non_front", "unreadable"}
VALID_OCR_QUALITIES  = {"good", "partial", "poor"}
NON_FRONT_STATUSES_V = {"not_applicable_non_front", "unreadable"}

# Image context → claim_extraction_status consistency mapping.
# These two fields are not independent — the validator enforces
# the contract rather than trusting two potentially contradictory
# LLM outputs (see validate_and_normalise).
FRONT_CONTEXTS = {"front_of_pack", "mixed_pack_text"}
NON_FRONT_CONTEXTS = {
    "ingredient_or_legal_panel",
    "nutrition_label",
    "price_sticker",
}


def validate_and_normalise(claims: dict) -> dict:
    """Normalise a raw LLM JSON response:
    - fill any missing boolean field with False;
    - validate enum fields (image_context, claim_extraction_status, ocr_quality);
    - enforce list types for list fields;
    - enforce no_claims_detected consistency;
    - for non-front images, zero out all claim fields.
    """
    # Validate / default enum fields
    ctx = claims.get("image_context", "uncertain")
    if ctx not in VALID_IMAGE_CONTEXTS:
        claims["image_context"] = "uncertain"
    status = claims.get("claim_extraction_status", "unreadable")
    if status not in VALID_CLAIM_STATUSES:
        claims["claim_extraction_status"] = "unreadable"
    quality = claims.get("ocr_quality", "poor")
    if quality not in VALID_OCR_QUALITIES:
        claims["ocr_quality"] = "poor"

    # Enforce image_context → claim_extraction_status consistency.
    # These fields are not independent: front_of_pack / mixed_pack_text
    # always implies "completed"; legal/nutrition/price panels always
    # imply "not_applicable_non_front"; uncertain implies "unreadable".
    # Capture the LLM's original status before any correction so the
    # audit flag can record whether an override was needed.
    _original_status = claims["claim_extraction_status"]
    _ctx = claims["image_context"]
    if _ctx in FRONT_CONTEXTS:
        claims["claim_extraction_status"] = "completed"
    elif _ctx in NON_FRONT_CONTEXTS:
        claims["claim_extraction_status"] = "not_applicable_non_front"
    elif _ctx == "uncertain":
        claims["claim_extraction_status"] = "unreadable"
    claims["status_normalised"] = (
        _original_status != claims["claim_extraction_status"]
    )

    # Fill missing booleans with False
    for field in BOOL_CLAIM_FIELDS:
        if field not in claims:
            claims[field] = False
        elif not isinstance(claims[field], bool):
            # null/None → False for claim fields (except no_claims_detected
            # which can be null for non-front images)
            if field != "no_claims_detected":
                claims[field] = bool(claims[field])

    # Enforce list fields
    for lf in ("fortification_nutrients", "sustainability_certs",
               "other_claims", "detected_claim_phrases"):
        if not isinstance(claims.get(lf), list):
            claims[lf] = []

    # For non-front images: zero out all claim booleans, set no_claims_detected=null
    if claims.get("claim_extraction_status") in NON_FRONT_STATUSES_V:
        for field in BOOL_CLAIM_FIELDS:
            if field != "no_claims_detected":
                claims[field] = False
        claims["no_claims_detected"] = None
        claims["fortification_nutrients"] = []
        claims["detected_claim_phrases"] = []

    # no_claims_detected consistency check for completed extractions
    if claims.get("claim_extraction_status") == "completed":
        has_any_claim = any(
            claims.get(f) is True
            for f in BOOL_CLAIM_FIELDS
            if f != "no_claims_detected"
        )
        if has_any_claim:
            claims["no_claims_detected"] = False
        elif claims.get("no_claims_detected") is None:
            claims["no_claims_detected"] = True

    return claims


def extract_claims(ocr_text: str, product_name: str = "",
                    max_retries: int = 3) -> tuple[dict, str]:
    """
    Send OCR text to Azure OpenAI for structured claim extraction.
    Retries up to max_retries times on HTTP 429 (rate limit), with a
    fixed 35s delay between attempts, before giving up — bounded so a
    sustained rate limit cannot recurse indefinitely.
    """
    if not OPENAI_ENDPOINT or not OPENAI_KEY:
        return {}, "no_credentials"

    if not ocr_text or len(ocr_text.strip()) < 10:
        return {"no_claims_detected": True, "ocr_quality": "poor"}, "skipped_empty"

    url = f"{OPENAI_ENDPOINT}/openai/v1/chat/completions"

    headers = {
        "api-key": OPENAI_KEY,
        "Content-Type": "application/json",
    }

    # Compute deterministic context hints (advisory — helps nano classify
    # the image type before the LLM sees the unstructured text)
    words = ocr_text.split()
    word_count = len(words)
    comma_count = ocr_text.count(",")
    semicolon_count = ocr_text.count(";")
    first_word = words[0].lower() if words else ""
    starts_with_ingredients = any(first_word.startswith(w) for w in
        ("ingredient", "ingrédient", "zutaten", "ingredienti", "ingrediënten"))
    nutrition_terms = sum(ocr_text.lower().count(t) for t in
        ("kcal", "kj", "protein", "protéine", "fat", "graisses", "carbohydrate",
         "glucide", "salt", "sel", "fibre", "/100g", "/100ml", "per serving"))
    currency_detected = any(c in ocr_text for c in ("€", "£", "$", "£/kg", "DH"))

    context_hints = (
        f"word_count={word_count}\n"
        f"comma_count={comma_count}\n"
        f"semicolon_count={semicolon_count}\n"
        f"starts_with_ingredients={str(starts_with_ingredients).lower()}\n"
        f"nutrition_term_count={nutrition_terms}\n"
        f"currency_detected={str(currency_detected).lower()}"
    )

    user_message = (
        f"Reference product name — context only, not claim evidence:\n{product_name}\n\n"
        f"Deterministic OCR context hints (advisory, not authoritative):\n{context_hints}\n\n"
        f"OCR text to analyse:\n{ocr_text[:2000]}"
    )

    body = {
        "model": OPENAI_DEPLOYMENT,
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user",   "content": user_message},
        ],
        "temperature": 0,
        "max_tokens": 800,
    }

    for attempt in range(max_retries):
        try:
            resp = requests.post(url, headers=headers, json=body, timeout=60)
            if resp.status_code == 200:
                content = resp.json()["choices"][0]["message"]["content"].strip()
                if content.startswith("```"):
                    content = content.split("```")[1]
                    if content.startswith("json"):
                        content = content[4:]
                claims = json.loads(content)
                claims = validate_and_normalise(claims)
                return claims, "success"
            elif resp.status_code == 429:
                if attempt < max_retries - 1:
                    time.sleep(35)
                    continue
                return {}, "rate_limited_max_retries"
            else:
                return {}, f"http_{resp.status_code}_{resp.text[:50]}"
        except json.JSONDecodeError:
            return {}, "json_parse_error"
        except Exception as e:
            return {}, f"error_{str(e)[:50]}"

    return {}, "max_retries"


# ── Cost tracker ──────────────────────────────────────────────────────────────

class CostTracker:
    def __init__(self, alert_chf: float):
        self.ocr_calls  = 0
        self.llm_calls  = 0
        self.alert_chf  = alert_chf
        self.aborted    = False

    @property
    def estimated_chf(self):
        return (self.ocr_calls * OCR_COST_PER_1K / 1000 +
                self.llm_calls * LLM_COST_PER_1K / 1000)

    def check_budget(self):
        if self.estimated_chf >= self.alert_chf:
            print(f"\n  COST ALERT: {self.estimated_chf:.2f} CHF >= {self.alert_chf} CHF limit")
            print(f"  Stopping to protect budget.")
            self.aborted = True
            return False
        return True

    def summary(self):
        print(f"\n  Cost summary:")
        print(f"    OCR calls:        {self.ocr_calls:,}")
        print(f"    LLM calls:        {self.llm_calls:,}")
        print(f"    Estimated spend:  {self.estimated_chf:.2f} CHF")
        print(f"    Remaining budget: {self.alert_chf - self.estimated_chf:.2f} CHF "
              f"(alert threshold: {self.alert_chf} CHF)")


# ── Main pipeline ─────────────────────────────────────────────────────────────

def find_latest_sample():
    """Find the clean-run sample or fall back to legacy smart_sample."""
    # v3+ clean run output takes precedence
    clean = SAMPLE_DIR / "sample_clean_run.csv"
    if clean.exists():
        return clean
    # Legacy pattern kept for backward compatibility
    files = sorted(SAMPLE_DIR.glob("smart_sample_*.csv"), reverse=True)
    if files:
        return files[0]
    raise FileNotFoundError(
        "No sample file found. Expected pipeline/sample_clean_run.csv "
        "(from smart_sample.py) or data/sample/smart_sample_*.csv."
    )


def enrich_sample_from_db(df: "pd.DataFrame", db_path) -> "pd.DataFrame":
    """Join product_name, primary_brand, image_url from DB by barcode.
    These fields should not be duplicated in the sampling CSV — the DB is
    the authoritative source for mutable product metadata. Falls back
    gracefully if DB is unavailable (test mode without DB)."""
    try:
        import sqlite3, pandas as pd
        conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
        fields = pd.read_sql_query(
            "SELECT barcode, product_name, primary_brand AS brands, image_url "
            "FROM products",
            conn, dtype={"barcode": str}
        )
        conn.close()
        # Drop any stale product columns from the CSV before joining
        drop_cols = [c for c in ("product_name", "brands", "image_url")
                     if c in df.columns]
        df = df.drop(columns=drop_cols)
        return df.merge(fields, on="barcode", how="left")
    except Exception as e:
        print(f"  WARNING: DB join for product fields failed ({e}); "
              f"product_name/brands/image_url may be empty.")
        return df


def load_checkpoint(checkpoint_path):
    """
    Load previously checkpointed results. Returns (records, barcodes) so
    completed rows can be carried into the final output on resume,
    rather than lost — see resume handling in main().
    """
    if checkpoint_path.exists():
        done = pd.read_csv(checkpoint_path, dtype={"barcode": str})
        return done.to_dict("records"), set(done["barcode"].tolist())
    return [], set()


def main():
    parser = argparse.ArgumentParser(description="Pack-image claim extraction")
    parser.add_argument("--test",   action="store_true",
                        help="Test mode: stratified 100-product sample (50 per region)")
    parser.add_argument("--resume", action="store_true",
                        help="Resume from checkpoint file")
    parser.add_argument("--input",  type=str, default=None,
                        help="Path to smart_sample CSV (default: auto-detect latest)")
    args = parser.parse_args()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    print(f"\nFood & Beverage Positioning Radar - vision_extract.py")
    print(f"Run timestamp: {timestamp}")

    # Validate credentials
    missing = []
    if not VISION_ENDPOINT:  missing.append("AZURE_VISION_ENDPOINT")
    if not VISION_KEY:       missing.append("AZURE_VISION_KEY")
    if not OPENAI_ENDPOINT:  missing.append("AZURE_OPENAI_ENDPOINT")
    if not OPENAI_KEY:       missing.append("AZURE_OPENAI_KEY")
    if missing:
        print(f"\n  ERROR: Missing environment variables:")
        for m in missing:
            print(f"    {m}")
        print(f"\n  Add them to .env or set them in your shell:")
        print(f"    set AZURE_VISION_ENDPOINT=https://your-resource.cognitiveservices.azure.com/")
        print(f"    set AZURE_VISION_KEY=your_key_here")
        print(f"    set AZURE_OPENAI_ENDPOINT=https://your-resource.openai.azure.com/")
        print(f"    set AZURE_OPENAI_KEY=your_key_here")
        sys.exit(1)

    # Load sample (v3+ uses pipeline/sample_clean_run.csv)
    input_path = Path(args.input) if args.input else find_latest_sample()
    print(f"  Input: {input_path.name}")
    df = pd.read_csv(input_path, dtype={"barcode": str})
    # Enrich with product_name/brands/image_url from DB (not duplicated in CSV)
    db_path = Path(__file__).resolve().parent.parent / "database" / "positioning_radar.db"
    df = enrich_sample_from_db(df, db_path)
    print(f"  Products in sample: {len(df):,}")

    # Test mode: stratified 100-row sample (50 per region)
    if args.test:
        # Column names match sample_clean_run.csv — verify if structure changes.
        _REGION_COL    = "sampling_region"
        _CATEGORY_COL  = "query_category"
        _COMPONENT_COL = "sample_component"       # backbone / matrix / calibration
        _PROXY_COL     = "has_positioning_signal"  # explicit positioning vs control
        _RISK_COL      = "non_front_risk"          # likely sticker / ingredient-panel image

        def _stratified_50(region_df: pd.DataFrame, seed: int = 42) -> pd.DataFrame:
            n_total = 50
            # Reserve ~10 rows with high non-front / sticker risk (key failure mode)
            if _RISK_COL in region_df.columns:
                high_risk = region_df[region_df[_RISK_COL] == True]
                safe      = region_df[region_df[_RISK_COL] != True]
            else:
                high_risk = pd.DataFrame()
                safe      = region_df
            n_risk    = min(10, len(high_risk))
            n_safe    = n_total - n_risk
            risk_rows = (high_risk.sample(n=n_risk, random_state=seed)
                         if n_risk > 0 else pd.DataFrame())
            # Stratify safe rows by component × category × positioning signal
            strata_cols = [c for c in [_COMPONENT_COL, _CATEGORY_COL, _PROXY_COL]
                           if c in safe.columns]
            if strata_cols and len(safe) > 0:
                grouped = safe.groupby(strata_cols, group_keys=False)
                safe_sample = (
                    grouped
                    .apply(lambda g: g.sample(
                        n=max(1, round(n_safe * len(g) / len(safe))),
                        random_state=seed
                    ))
                    .sample(frac=1, random_state=seed)
                    .head(n_safe)
                )
                if len(safe_sample) < n_safe:
                    top_up = (safe.drop(safe_sample.index)
                              .sample(n=min(n_safe - len(safe_sample),
                                           len(safe) - len(safe_sample)),
                                      random_state=seed))
                    safe_sample = pd.concat([safe_sample, top_up])
            else:
                safe_sample = safe.sample(n=min(n_safe, len(safe)), random_state=seed)
            return (pd.concat([risk_rows, safe_sample])
                    .sample(frac=1, random_state=seed))

        if _REGION_COL in df.columns:
            df = (df.groupby(_REGION_COL, group_keys=False)
                    .apply(_stratified_50)
                    .reset_index(drop=True))
            region_counts = df[_REGION_COL].value_counts().to_dict()
        else:
            df = df.sample(n=min(100, len(df)), random_state=42).reset_index(drop=True)
            region_counts = {}

        print(f"  TEST MODE: {len(df)} stratified products "
              f"({', '.join(f'{r}: {c}' for r, c in sorted(region_counts.items()))})")
        if _COMPONENT_COL in df.columns:
            print(f"  Components: {df[_COMPONENT_COL].value_counts().to_dict()}")
        if _CATEGORY_COL in df.columns:
            print(f"  Categories: {df[_CATEGORY_COL].value_counts().to_dict()}")

    # Checkpoint / resume
    output_path = SAMPLE_DIR / f"vision_results_{timestamp}.csv"
    checkpoint_path = SAMPLE_DIR / "vision_results_checkpoint.csv"

    results = []
    if args.resume and checkpoint_path.exists():
        results, done_barcodes = load_checkpoint(checkpoint_path)
        df = df[~df["barcode"].isin(done_barcodes)]
        print(f"  Resuming: {len(done_barcodes):,} already done (carried into "
              f"final output), {len(df):,} remaining")
        output_path = checkpoint_path

    print(f"  Output: {output_path.name}")
    print(f"  Cost alert at: {COST_ALERT_CHF} CHF\n")

    tracker = CostTracker(COST_ALERT_CHF)

    for i, row in enumerate(df.itertuples(), 1):
        if not tracker.check_budget():
            break

        barcode     = str(row.barcode)
        product     = str(getattr(row, "product_name", "") or "")
        brand       = str(getattr(row, "brands", "") or "")
        image_url   = str(getattr(row, "image_url", "") or "")
        # Carry all sampling metadata columns through to the output row.
        # This replaces the obsolete "tier" field and preserves the full
        # stratification context (component, stratum, weights, reality
        # bands, positioning proxy, etc.) needed for later modelling.
        sampling_meta = {
            col: getattr(row, col, None)
            for col in df.columns
            if col not in ("barcode", "product_name", "brands", "image_url")
        }

        print(f"  [{i:>5}/{len(df)}] {brand[:25]:<25} {product[:30]:<30}", end=" ")

        # Stage 1: OCR
        ocr_text, ocr_status = ocr_image(image_url)
        tracker.ocr_calls += 1

        # Stage 2: LLM claim extraction
        claims, llm_status = {}, "skipped"
        if ocr_status == "success" and ocr_text:
            claims, llm_status = extract_claims(ocr_text, product)
            tracker.llm_calls += 1

        print(f"OCR:{ocr_status:<12} LLM:{llm_status:<12} "
              f"cost:{tracker.estimated_chf:.3f} CHF")

        result = {
            **sampling_meta,  # all sampling metadata passes through first
            "barcode":       barcode,
            "product_name":  product,
            "brands":        brand,
            "image_url":     image_url,
            # pack_analysis_attempted=1 means this product was submitted
            # for image-based extraction, regardless of OCR/LLM outcome —
            # see docs/COLUMN_DESCRIPTIONS.md.
            "pack_analysis_attempted":  1,
            "vision_model":             OPENAI_DEPLOYMENT,
            "prompt_version":           PROMPT_VERSION,
            "pack_analysis_timestamp":  timestamp,
            "ocr_text":      ocr_text,
            "ocr_status":    ocr_status,
            "llm_status":    llm_status,
            "claims_json":   json.dumps(claims) if claims else "",
        }

        # The v3_* fields below mirror the locked extraction prompt and
        # are intermediate/debug pipeline outputs, not final schema
        # names. merge_scores.py and tag_claims.py translate these into
        # the neutral, user-facing taxonomy (pack_claims_found,
        # claim_category_1, claim_category_2, nutrition_benchmark_flags,
        # claim_benchmark_intersections — see docs/COLUMN_DESCRIPTIONS.md).
        # Raw keys such as sustainability_halo or glp1_positioning are
        # extraction-schema keys only and should not be treated as final
        # product language in the UI, README, or Power BI deck.
        # ocr_quality is "good"/"partial"/"poor" only (v4+).
        # image_context: front_of_pack/mixed_pack_text/ingredient_or_legal_panel/
        #   nutrition_label/price_sticker/uncertain.
        # claim_extraction_status: completed/not_applicable_non_front/unreadable.
        if claims:
            for key in [
                # Core claim booleans
                "protein_claim", "sugar_free_claim", "reduced_sugar",
                "no_palm_oil", "no_artificial", "natural_claim",
                "fortification_claim", "fibre_claim",
                # Gut health (three distinct fields)
                "gut_health_claim", "probiotic_claim", "prebiotic_claim",
                # Immunity (separate from fortification)
                "immune_claim",
                # Energy, sleep, brain/cognitive
                "energy_claim", "sleep_claim", "brain_health_claim",
                # Reduced fat and whole grain
                "reduced_fat_claim", "whole_grain_claim",
                # Free-from identity
                "vegan_claim", "organic_claim", "dairy_free_claim", "lactose_free_claim",
                "gluten_free_claim", "plant_based_claim",
                # Other functional / positioning
                "vitalite_concept", "sustainability_halo", "reformulation_claim",
                "comparative_claim", "glp1_positioning",
                "origin_quality_claim", "clean_label_claim", "minimal_ingredients_claim",
                "artisan_claim", "heritage_claim", "gender_targeting_claim",
                # Image context and extraction status
                "image_context", "claim_extraction_status",
                # Readability / formatting metadata
                "no_claims_detected", "ocr_quality",
                # Audit: True if validator overrode LLM claim_extraction_status
                "status_normalised",
                # Numeric / string fields
                "protein_amount_g", "sugar_reduction_pct", "fat_reduction_pct",
                "comparative_reference",
            ]:
                result[f"v3_{key}"] = claims.get(key)
            result["v3_fortification_nutrients"] = "|".join(
                claims.get("fortification_nutrients", []) or []
            )
            result["v3_sustainability_certs"] = "|".join(
                claims.get("sustainability_certs", []) or []
            )
            result["v3_other_claims"] = "|".join(
                claims.get("other_claims", []) or []
            )
            result["v3_detected_claim_phrases"] = "|".join(
                claims.get("detected_claim_phrases", []) or []
            )

        results.append(result)

        # Save checkpoint every 50 products
        if i % 50 == 0:
            pd.DataFrame(results).to_csv(
                checkpoint_path, index=False, encoding="utf-8-sig"
            )

        # Small delay to be polite to Azure
        time.sleep(1.5)  # RPM 50 — 1.2s minimum + small buffer

    # Final save
    results_df = pd.DataFrame(results)
    results_df.to_csv(output_path, index=False, encoding="utf-8-sig")

    print(f"\n  -- Summary --------------------------------------------------")
    print(f"  Products processed: {len(results_df):,}")
    if len(results_df):
        ocr_ok  = (results_df["ocr_status"] == "success").sum()
        llm_ok  = (results_df["llm_status"] == "success").sum()
        print(f"  OCR success:        {ocr_ok:,} ({ocr_ok/len(results_df)*100:.0f}%)")
        print(f"  LLM success:        {llm_ok:,} ({llm_ok/len(results_df)*100:.0f}%)")

        if "v3_no_claims_detected" in results_df.columns:
            no_claims = results_df["v3_no_claims_detected"].sum()
            results_df_s = pd.DataFrame(results)
            if "v3_claim_extraction_status" in results_df_s.columns:
                completed = results_df_s["v3_claim_extraction_status"] == "completed"
                print(f"  claim_extraction_status:")
                for ctx, cnt in results_df_s["v3_claim_extraction_status"].value_counts().items():
                    print(f"    {ctx}: {cnt:,}")
                if "v3_image_context" in results_df_s.columns:
                    print(f"  image_context (front-of-pack / non-front):")
                    for ctx, cnt in results_df_s["v3_image_context"].value_counts().items():
                        print(f"    {ctx}: {cnt:,}")
                with_claims = (completed & (results_df_s.get("v3_no_claims_detected", True) == False)).sum()
                no_claims_front = (completed & (results_df_s.get("v3_no_claims_detected", False) == True)).sum()
                print(f"  Completed front packs WITH claims: {with_claims:,}")
                print(f"  Completed front packs NO claims:   {no_claims_front:,}")
            else:
                has_claims = llm_ok - no_claims
                print(f"  Products with claims: {has_claims:,}")
            print(f"  Products no claims:   {int(no_claims):,}")

    tracker.summary()
    if tracker.aborted:
        print(f"\n  Run was stopped by cost alert.")
        print(f"  Resume with: python pipeline/vision_extract.py --resume")

    print(f"\n  Saved -> {output_path.name}")
    print(f"  Next step: python pipeline/merge_scores.py\n")


if __name__ == "__main__":
    main()
