-- schema.sql
-- Auto-generated by pipeline/export_schema.py — do not edit by hand.
-- Generated: 2026-06-20 13:35:02
-- Source: database/positioning_radar.db

-- ── Tables ───────────────────────────────────────────────────

CREATE TABLE ingestion_log (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    run_timestamp     TEXT,
    source            TEXT,    -- 'api' or 'bulk_export'
    input_file        TEXT,
    category          TEXT,    -- 'all' or specific category
    rows_in_file      INTEGER,
    products_inserted INTEGER,
    products_updated  INTEGER,
    analysis_inserted INTEGER,
    analysis_updated  INTEGER,
    status            TEXT,    -- 'success' / 'partial' / 'failed'
    notes             TEXT
);

CREATE TABLE positioning_example_products (
    id                              INTEGER PRIMARY KEY AUTOINCREMENT,
    barcode                         TEXT,
    product_name                    TEXT,
    primary_brand                   TEXT,
    query_category                  TEXT,
    claim_category_1                TEXT,
    claim_category_2                TEXT,
    pack_claims_found               TEXT,
    nutrition_benchmark_flags       TEXT,
    claim_benchmark_intersections   TEXT,
    positioning_composition_gap     REAL,
    composition_marker_score        REAL,
    nova_group                      REAL,
    nutriscore_grade                TEXT,
    image_url                       TEXT,
    selection_reason                TEXT,
    run_timestamp                   TEXT
);

CREATE TABLE product_analysis (
    barcode                               TEXT PRIMARY KEY,

    -- Ingredient composition markers (analyze.py, Component A)
    processing_marker_count                 INTEGER,
    processing_markers_found                 TEXT,
    processing_marker_max_severity             INTEGER,
    has_processing_markers                  INTEGER,   -- 1/0 boolean
    e_number_count                        INTEGER,
    e_numbers_found                        TEXT,
    has_artificial_sweetener                 INTEGER,   -- 1/0 boolean
    composition_marker_score                 REAL,
    composition_marker_band                  TEXT,

    -- Ingredient/name-based claim signals (analyze.py)
    ingredient_based_claim_signal_count         INTEGER,
    ingredient_based_claim_signals_found         TEXT,
    absence_reduction_claim_count             INTEGER,
    absence_reduction_claims_found             TEXT,

    -- Named intersection patterns (analyze.py)
    sugar_positioning_intersection_flag          INTEGER,   -- 1/0
    protein_fat_intersection_flag              INTEGER,
    fibre_sugar_processing_intersection_flag       INTEGER,
    plant_based_nutrition_intersection_flag       INTEGER,

    -- Pack-image extraction metadata (populated by merge_scores.py)
    pack_analysis_attempted                 INTEGER,   -- 1/0, whether
                                                        -- this product was
                                                        -- submitted for
                                                        -- image extraction
    ocr_text                              TEXT,
    ocr_status                             TEXT,
    llm_status                             TEXT,
    vision_model                           TEXT,
    prompt_version                         TEXT,
    pack_analysis_timestamp                  TEXT,
    pack_claims_found                       TEXT,
    claim_source                           TEXT,      -- 'vision' or 'nlp_only'

    -- Claim taxonomy (populated by tag_claims.py)
    claim_category_1                        TEXT,
    claim_category_2                        TEXT,

    -- Benchmark flags and intersections (populated by tag_claims.py)
    nutrition_benchmark_flags                 TEXT,
    claim_benchmark_intersections              TEXT,

    -- Positioning-to-composition gap (populated by merge_scores.py)
    positioning_composition_gap               REAL,
    positioning_composition_gap_band            TEXT,

    -- Planned, not yet implemented
    product_segment_label                   TEXT,      -- null until v2 K-Means

    analyzed_at                           TEXT,      -- when this row was
                                                       -- last computed/updated

    FOREIGN KEY (barcode) REFERENCES products(barcode)
);

CREATE TABLE products (
    barcode                      TEXT PRIMARY KEY,
    product_name                 TEXT,
    brands                       TEXT,
    primary_brand                 TEXT,
    quantity                     TEXT,
    packaging                    TEXT,
    query_category                TEXT,
    off_categories                 TEXT,
    countries                    TEXT,
    primary_country                TEXT,
    labels                       TEXT,
    ingredients_text               TEXT,
    additives_tags                 TEXT,
    energy_kcal                  REAL,
    fat_100g                     REAL,
    saturated_fat_100g             REAL,
    carbs_100g                   REAL,
    sugars_100g                  REAL,
    fiber_100g                   REAL,
    protein_100g                  REAL,
    salt_100g                    REAL,
    nutriscore_grade               TEXT,
    nova_group                   REAL,
    completeness_score             INTEGER,
    ingredients_lang               TEXT,
    ingredient_analysis_eligible     INTEGER,   -- 1/0 boolean
    created_t                    TEXT,
    last_modified_t                TEXT,
    ingested_at                   TEXT,      -- when this row was loaded by us
    image_url                    TEXT       -- front-of-pack image URL, used
                                             -- for pack-image claim extraction
);

CREATE TABLE weekly_brand_positioning_summary (
    id                                      INTEGER PRIMARY KEY AUTOINCREMENT,
    week_ending                             TEXT,
    run_timestamp                           TEXT,
    source_scope                            TEXT,
    primary_brand                           TEXT,
    query_category                          TEXT,
    product_count                           INTEGER,
    pack_analyzed_count                     INTEGER,
    pct_pack_analyzed                       REAL,
    pct_with_pack_claims                    REAL,
    pct_with_pack_claims_among_analyzed     REAL,
    positioning_gap_scored_count            INTEGER,
    pct_positioning_gap_scored              REAL,
    claim_tagged_count                      INTEGER,
    pct_claim_tagged                        REAL,
    pct_functional                          REAL,
    pct_free_of                             REAL,
    pct_natural_organic                     REAL,
    pct_other_claim                         REAL,
    pct_no_claim                            REAL,
    top_claim_category_1                    TEXT,
    top_claim_category_2                    TEXT,
    top_detected_claim_category_1           TEXT,
    top_detected_claim_category_2           TEXT,
    avg_composition_marker_score            REAL,
    avg_positioning_composition_gap         REAL,
    pct_nova4                               REAL,
    pct_with_nutrition_benchmark_flags      REAL,
    pct_with_claim_benchmark_intersections  REAL,
    pct_with_artificial_sweetener           REAL,
    pct_sugar_above_reference               REAL,
    pct_saturated_fat_above_reference       REAL,
    pct_fat_above_reference                 REAL,
    pct_salt_above_reference                REAL
);

CREATE TABLE weekly_brand_summary (
    id                                  INTEGER PRIMARY KEY AUTOINCREMENT,
    week_ending                          TEXT,      -- ISO date of week end
    primary_brand                        TEXT,
    query_category                        TEXT,
    product_count                        INTEGER,
    avg_composition_marker_score             REAL,
    pct_nova4                           REAL,
    pct_with_ingredient_based_claim_signals     REAL,
    pct_with_artificial_sweetener            REAL,
    top_ingredient_based_claim_signal         TEXT,
    run_timestamp                         TEXT
);

-- ── Indexes ──────────────────────────────────────────────────

CREATE INDEX idx_analysis_band ON product_analysis(composition_marker_band);

CREATE INDEX idx_analysis_score ON product_analysis(composition_marker_score);

CREATE INDEX idx_pep_reason ON positioning_example_products(selection_reason);

CREATE INDEX idx_products_brand ON products(brands);

CREATE INDEX idx_products_category ON products(query_category);

CREATE INDEX idx_products_country ON products(primary_country);

CREATE INDEX idx_products_modified ON products(last_modified_t);

CREATE INDEX idx_products_nova ON products(nova_group);

CREATE INDEX idx_products_primary_brand ON products(primary_brand);

CREATE INDEX idx_wbps_brand ON weekly_brand_positioning_summary(primary_brand);

CREATE INDEX idx_wbps_week ON weekly_brand_positioning_summary(week_ending);

